
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AkGida_MyInfo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Baby
{

    public int BabyID { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string ImagePath { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

}

}
