
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AkGida_MyInfo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CompanyDuyuru
{

    public int CompanyDuyuruID { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public Nullable<int> DuyuruID { get; set; }



    public virtual Companies Companies { get; set; }

    public virtual Duyurular Duyurular { get; set; }

}

}
