//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkGida_MyInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companies()
        {
            this.CompanyDuyuru = new HashSet<CompanyDuyuru>();
            this.Departments = new HashSet<Departments>();
            this.YemekSirketi = new HashSet<YemekSirketi>();
        }

       
        public int CompanyID { get; set; }
        [Display(Name ="Þube")]
        public string CompanyName { get; set; }
        [Display(Name = "Þube Adresi")]
        public string CompanyAddress { get; set; }
        [Display(Name = "Þube Türü")]
        public string CompanyType { get; set; }
        [Display(Name = "Telefon No")]
        public string CompanyTel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDuyuru> CompanyDuyuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YemekSirketi> YemekSirketi { get; set; }
    }
}
