//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkGida_MyInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Duyurular
    {
        public int DuyuruID { get; set; }
        [Display(Name = "Lokasyon")]
        public Nullable<int> CompanyID { get; set; }
        [Display(Name = "Başlık")]
        public string Baslik { get; set; }
        [Display(Name = "İçerik")]
        public string Icerik { get; set; }
        [Display(Name = "Başlangıç Tarihi")]
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        [Display(Name = "Bitiş Tarihi")]
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        [Display(Name = "Resim Yolu")]
        public string ResimYolu { get; set; }
        [Display(Name = "Lokasyon")]
        public virtual Companies Companies { get; set; }
    }
}
