
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AkGida_MyInfo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Duyurular
{

    public int DuyuruID { get; set; }

    public string Baslik { get; set; }

    public string Icerik { get; set; }

    public Nullable<System.DateTime> BaslangicTarihi { get; set; }

    public Nullable<System.DateTime> BitisTarihi { get; set; }

    public string ResimYolu { get; set; }

    public Nullable<int> CompanyID { get; set; }



    public virtual Companies Companies { get; set; }

}

}
