//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkGida_MyInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personels
    {
        public int PersonelID { get; set; }
        [Display(Name = "Adı")]
        public string PersonelName { get; set; }
        [Display(Name = "Soyadı")]
        public string PersonelSurname { get; set; }
        public string Corbus { get; set; }
        [Display(Name = "Dahili Numara")]
        public string PersonelDahiliNo { get; set; }
        [Display(Name = "Telefon")]
        public string PersonelTel { get; set; }
        [Display(Name = "E-posta")]
        public string PersonelEposta { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        [Display(Name = "Doğum Tarihi")]
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
