
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AkGida_MyInfo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Personels
{

    public int PersonelID { get; set; }

    public string PersonelName { get; set; }

    public string PersonelSurname { get; set; }

    public string Corbus { get; set; }

    public string PersonelDahiliNo { get; set; }

    public string PersonelTel { get; set; }

    public string PersonelEposta { get; set; }

    public Nullable<int> DepartmentID { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }



    public virtual Departments Departments { get; set; }

}

}
