//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkGida_MyInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yayinlar
    {
        public int YayinID { get; set; }
        public string YayinBaslik { get; set; }
        public string YayinURL { get; set; }
    }
}
