//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkGida_MyInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class YeniUrun
    {
        public int UrunID { get; set; }
        [Display(Name = "Ürün Adı")]
        public string UrunAdi { get; set; }
        [Display(Name = "Tanıtım")]
        public string Tanitim { get; set; }
        [Display(Name = "Resim Yolu")]
        public string ResimYolu { get; set; }
        [Display(Name = "Video Yolu")]
        public string VideoYolu { get; set; }
    }
}
